blank_issues_enabled: false
contact_links:
  - name: ğŸ˜ Contribution Guide
    url: https://github.com/carloscuesta/react-native-error-boundary/blob/master/.github/CONTRIBUTING.md#contributing-to-gitmoji
    about: Please read through before making any contribution.
